
###
GET localhost:8080/api/articulos
###
GET localhost:8080/api/articulos/2
###
POST localhost:8080/saveProducto

###
POST localhost:8080/api/articulos
Content-Type: application/json

{
  "nombre": "lapiz",
  "unidades": 25,
  "precio": 4
}

###
GET localhost:8080/api/articulos/2/6

###
PUT localhost:8080/api/articulos/70
Content-Type: application/x-www-form-urlencoded

nombre="nuevonombre"
cantidad=17
Color="rojo"

###
DELETE localhost:8080/api/articulos/1

###
DELETE localhost:8080/admin/1
###