GET localhost:8080/Producto
###
GET localhost:8080/Producto/1
###
#POST localhost:8080/Producto/saveProducto

###
POST localhost:8080/Producto
Content-Type: application/json

{
  "nombre": "lapiz",
  "unidades": 25,
  "precio": 4
}

###
GET localhost:8080/Producto/1/1

###
PUT localhost:8080/Producto/70
Content-Type: application/x-www-form-urlencoded

nombre="nuevonombre"
cantidad=17
Color="rojo"

###
DELETE localhost:8080/Producto/1

###