INSERT INTO PRODUCTO ( PRECIO, UNIDADES, NOMBRE, IMAGEN) VALUES ( 4, 6,'Boli','Boli.jpg');
INSERT INTO PRODUCTO ( PRECIO, UNIDADES, NOMBRE, IMAGEN) VALUES ( 1, 2,'Goma','Milan430.jpg');
INSERT INTO PRODUCTO ( PRECIO, UNIDADES, NOMBRE, IMAGEN) VALUES ( 4, 6,'folio','folio.jpg');
INSERT INTO PRODUCTO ( PRECIO, UNIDADES, NOMBRE, IMAGEN) VALUES ( 1, 2,'lapiz','lapiz.png');

