// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvFLUH8OO_lO0QFHAGOQiHeXzGVHud_o',
    appId: '1:1090506133860:web:1aaf7d9c8d500a7c266a71',
    messagingSenderId: '1090506133860',
    projectId: 'proyectoadriantebar',
    authDomain: 'proyectoadriantebar.firebaseapp.com',
    storageBucket: 'proyectoadriantebar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPatgzIWsgC_bZIJzNzO5zahbmyLg9Ew',
    appId: '1:1090506133860:android:dc6c59fda33a6852266a71',
    messagingSenderId: '1090506133860',
    projectId: 'proyectoadriantebar',
    storageBucket: 'proyectoadriantebar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3RNZ7CXy6CIhcwbdztZ1XsMqFjx8Qqhs',
    appId: '1:1090506133860:ios:2efbdc9782f631db266a71',
    messagingSenderId: '1090506133860',
    projectId: 'proyectoadriantebar',
    storageBucket: 'proyectoadriantebar.appspot.com',
    iosBundleId: 'com.example.adriantebar1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3RNZ7CXy6CIhcwbdztZ1XsMqFjx8Qqhs',
    appId: '1:1090506133860:ios:745a266e76331a7b266a71',
    messagingSenderId: '1090506133860',
    projectId: 'proyectoadriantebar',
    storageBucket: 'proyectoadriantebar.appspot.com',
    iosBundleId: 'com.example.adriantebar1.RunnerTests',
  );
}
